version: "3.8"

services:
  mmark:
    build: .
    working_dir: /work
    volumes:
      - ./:/work
    environment:
      - INPUT=src/main.md
      - XML_OUT=docs/index.xml
      - FORMAT=html
    tty: true
